### ISSUE TITLE
Consider using apt module rather than running apt-get

### ISSUE THREAD

**Issue by davidak** [Oefenweb/ansible-apt#15]
```
TASK [tersmitten.apt : clean] **************************************************
ok: [dev-ansible-trusty]
 [WARNING]: Consider using apt module rather than running apt-get
```

only on trusty, not on precise or xenial.

**Comment by tersmitten** [comment]
That's not compatible with Ansible < 2. Is there a clean command in version >= 2?

**Comment by davidak** [comment]
I don't see a `clean` command there.

https://docs.ansible.com/ansible/apt_module.html

We use the latest version (2.1.1.0).

**Comment by davidak** [comment]
The output is produced by Ansibles apt module.

related to https://github.com/ansible/ansible-modules-core/issues/4201
