### ISSUE TITLE
How to select backports version?

### ISSUE THREAD

**Issue by esprit-libre** [Oefenweb/ansible-apt#36]
Hello,

many thanks for this usefull role!

I don't know how to install backport version for a specific paquet?

For now, I use in Debian 10:
```yaml
apt_install:
  - msmtp
  - coturn
```

I want to use version 1.8.11 version of msmtp (available in backports) instead of 1.8.3, but I want to keep coturn distro version.

Thanks for your help

**Comment by tersmitten** [comment]
I don't think that's supported (yet)

**Comment by esprit-libre** [comment]
Ok. I will try another way...

**Comment by tersmitten** [comment]
Ok
