### ISSUE TITLE
No package matching 'aptitude' is available

### ISSUE THREAD

**Issue by tersmitten** [Oefenweb/ansible-apt#7]

**Comment by davidak** [comment]
```
failed: [dev-ansible-xenial] (item=[u'python-apt', u'aptitude']) => {"failed": true, "item": ["python-apt", "aptitude"], "msg": "No package matching 'aptitude' is available"}
```

I had to `apt update` to be able to find **aptitude** with `apt search aptitude`.

So the cache was not updates because it already was updated, but not after the sources changed.
You should force an update after changing the sources file.

**Comment by tersmitten** [comment]
Aptitude is a requirement from the [apt module](http://docs.ansible.com/ansible/apt_module.html)

**Comment by tersmitten** [comment]
Can you make a pull request with a bugfix?

**Comment by davidak** [comment]
Thanks.

I will make a PR tomorrow!

**Comment by davidak** [comment]
I got some 404 errors with the default sources mirror setting on Ubuntu 12.04 because not all mirrors have a repo for it.

http://ubuntu.unitedcolo.de/ubuntu/dists/

```
W: Failed to fetch mirror://mirrors.ubuntu.com/mirrors.txt/dists/precise/universe/binary-amd64/Packages  404  Not Found [Mirror: http://ubuntu.unitedcolo.de/ubuntu/]
```

Solution is to use a mirror that has every version you need.
